import { Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../@components/banner/Banner";
import Blogs from "../@components/blogs/Blogs";
import Clients from "../@components/clients/Clients";
import ContactUs from "../@components/contactus/ContactUs";
import Stories from "../@components/stories/Stories";
import WhatWeDo from "../@components/whatWeDo/WhatWeDo";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <WhatWeDo />
      <Stories />
      <Clients />
      <Blogs />
      <ContactUs />
    </Box>
  );
};

export default Home;

